// Icons embedded at compile time. Registered into the wxMemoryFSHandler
// virtual filesystem so they can be loaded with memory:icons/name.svg
// on every platform with zero path lookup.

#include <wx/filesys.h>
#include <wx/fs_mem.h>

namespace {

// Include xxd-generated byte arrays.
#include "icons_deepseek.inc"
#include "icons_opencode.inc"
#include "icons_plus.inc"
#include "icons_settings.inc"

struct IconEntry {
    const char* name;
    const unsigned char* data;
    unsigned int len;
};

const IconEntry kIcons[] = {
    {"deepseek.svg", icon_deepseek_svg, icon_deepseek_svg_len},
    {"opencode.svg", icon_opencode_svg, icon_opencode_svg_len},
    {"plus.svg",     icon_plus_svg,     icon_plus_svg_len},
    {"settings.svg", icon_settings_svg, icon_settings_svg_len},
};

bool iconsRegistered = false;

}  // namespace

void RegisterEmbeddedIcons() {
    if (iconsRegistered) return;
    wxMemoryFSHandler::AddFile("memory:icons/deepseek.svg",
        wxMemoryFSHandler::DecToMemBlock(icon_deepseek_svg, icon_deepseek_svg_len));
    wxMemoryFSHandler::AddFile("memory:icons/opencode.svg",
        wxMemoryFSHandler::DecToMemBlock(icon_opencode_svg, icon_opencode_svg_len));
    wxMemoryFSHandler::AddFile("memory:icons/plus.svg",
        wxMemoryFSHandler::DecToMemBlock(icon_plus_svg, icon_plus_svg_len));
    wxMemoryFSHandler::AddFile("memory:icons/settings.svg",
        wxMemoryFSHandler::DecToMemBlock(icon_settings_svg, icon_settings_svg_len));
    iconsRegistered = true;
}
