// Icons embedded at compile time. Registered into the wxMemoryFSHandler
// virtual filesystem so they can be loaded with memory:icons/name.svg
// on every platform with zero path lookup.

#include <wx/filesys.h>
#include <wx/fs_mem.h>

namespace {

// Include xxd-generated byte arrays (variable names: icon_<name>_svg, icon_<name>_svg_len).
#include "icons_deepseek.inc"
#include "icons_opencode.inc"
#include "icons_plus.inc"
#include "icons_settings.inc"

bool iconsRegistered = false;

}  // namespace

void RegisterEmbeddedIcons() {
    if (iconsRegistered) return;
    wxMemoryFSHandler::AddFile("memory:icons/deepseek.svg",
        icon_deepseek_svg, icon_deepseek_svg_len);
    wxMemoryFSHandler::AddFile("memory:icons/opencode.svg",
        icon_opencode_svg, icon_opencode_svg_len);
    wxMemoryFSHandler::AddFile("memory:icons/plus.svg",
        icon_plus_svg, icon_plus_svg_len);
    wxMemoryFSHandler::AddFile("memory:icons/settings.svg",
        icon_settings_svg, icon_settings_svg_len);
    iconsRegistered = true;
}
